// Code generated by hertz generator.

package postersapi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _posterserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuniqueusernamesMw() []app.HandlerFunc {
	// your code...
	return nil
}
