// Code generated by hertz generator.

package viewersapi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _viewerserviceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuniqueviewernamesMw() []app.HandlerFunc {
	// your code...
	return nil
}
