// Code generated by hertz generator.

package echoapi

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _echoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _echo0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
